name: generate animation

on:
  # Roda automaticamente a cada 24 horas
  schedule:
    - cron: "0 */24 * * *" 
  
  # Permite rodar manualmente a qualquer momento
  workflow_dispatch:
  
  # Roda a cada push na branch master
  push:
    branches:
    - master

jobs:
  generate:
    permissions: 
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
      # Gera o jogo da cobrinha a partir das contribuições do usuário
      - name: generate github-contribution-grid-snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            # Versão clara: Cobra rosa
            dist/github-contribution-grid-snake.svg?color_snake=#ff69b4
            
            # Versão escura: Cobra rosa e quadradinhos em tons de rosa
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark&color_snake=#ff69b4&color_dots=#161b22,#f190bc,#ec63a5,#e0368c,#9e165f
          
      # Envia o conteúdo gerado na pasta <dist> para a branch 'output'
      - name: push github-contribution-grid-snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
